version: '3.8'

services:
  userservice_db:
    image: postgres:latest
    container_name: userservice_postgres
    environment:
      POSTGRES_USER: userservice
      POSTGRES_PASSWORD: userservicepass
      POSTGRES_DB: userservicedb
    volumes:
      - userservice_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - user_service_network

  userservice:
    build: ./UserService
    depends_on:
      - userservice_db
    ports:
      - "5001:5001"
    networks:
      - proxy_network
      - user_service_network
  
  postservice_db:
    image: postgres:latest
    container_name: postservice_postgres
    environment:
      POSTGRES_USER: postservice
      POSTGRES_PASSWORD: postservicepass
      POSTGRES_DB: postservicedb
    volumes:
      - postservice_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - post_service_network

  post_service:
    build: ./PostService
    depends_on:
      - postservice_db
    environment:
      - DATABASE_USER=postservice
      - DATABASE_PASSWORD=postservicepass
      - DATABASE_HOST=postservice_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postservicedb
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
    ports:
      - "50051:50051"
    networks:
      - proxy_network
      - post_service_network

  proxyservice:
    build: ./APIGateway
    ports:
      - "5000:5000"
    networks:
      - proxy_network
      - user_service_network
      - post_service_network
    depends_on:
      - userservice

  tests:
    build: ./tests
    networks:
      - proxy_network
    depends_on:
      - proxyservice

networks:
  post_service_network:
    driver: bridge
  user_service_network:
    driver: bridge
  proxy_network:
    driver: bridge

volumes:
  userservice_postgres_data:
  postservice_postgres_data:
