version: '3.8'

services:
  userservice_db:
    image: postgres:latest
    container_name: userservice_postgres
    environment:
      POSTGRES_USER: userservice
      POSTGRES_PASSWORD: userservicepass
      POSTGRES_DB: userservicedb
    volumes:
      - userservice_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - user_service_network

  userservice:
    build: ./UserService
    depends_on:
      - userservice_db
    ports:
      - "5001:5001"
    networks:
      - proxy_network
      - user_service_network

  postservice_db:
    image: postgres:latest
    container_name: postservice_postgres
    environment:
      POSTGRES_USER: postservice
      POSTGRES_PASSWORD: postservicepass
      POSTGRES_DB: postservicedb
    volumes:
      - postservice_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - post_service_network

  post_service:
    build: ./PostService
    depends_on:
      - postservice_db
    environment:
      - DATABASE_USER=postservice
      - DATABASE_PASSWORD=postservicepass
      - DATABASE_HOST=postservice_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postservicedb
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
    ports:
      - "50051:50051"
    networks:
      - proxy_network
      - post_service_network

  proxyservice:
    build: ./APIGateway
    ports:
      - "5000:5000"
    networks:
      - proxy_network
      - user_service_network
      - post_service_network
    depends_on:
      - userservice

  version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c "
        cub kafka-ready -b kafka:9092 1 30 &&
        kafka-topics --create --if-not-exists --topic registration_events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic like_click_events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic view_events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
        kafka-topics --create --if-not-exists --topic comment_events --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
      "

  tests:
    build: ./tests
    networks:
      - proxy_network
    depends_on:
      - proxyservice

networks:
  post_service_network:
    driver: bridge
  user_service_network:
    driver: bridge
  proxy_network:
    driver: bridge

volumes:
  userservice_postgres_data:
  postservice_postgres_data:
